INFO:kivy:Logger: Record log in C:\Users\Sethhobratschk\.kivy\logs\kivy_21-08-24_0.txt
INFO:kivy:deps: Successfully imported "kivy_deps.angle" 0.1.9
INFO:kivy:deps: Successfully imported "kivy_deps.glew" 0.1.12
INFO:kivy:deps: Successfully imported "kivy_deps.sdl2" 0.1.22
INFO:kivy:Kivy: v1.11.1
INFO:kivy:Kivy: Installed at "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\__init__.py"
INFO:kivy:Python: v3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
INFO:kivy:Python: Interpreter at "C:\Program Files (x86)\Python37-32\python.exe"
INFO:kivy:Factory: 184 symbols loaded
INFO:kivy:Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
INFO:kivy:Window: Provider: sdl2
INFO:kivy:GL: Using the "OpenGL" graphics system
INFO:kivy:GL: GLEW initialization succeeded
INFO:kivy:GL: Backend used <glew>
INFO:kivy:GL: OpenGL version <b'4.6.0 - Build 27.20.100.8681'>
INFO:kivy:GL: OpenGL vendor <b'Intel'>
INFO:kivy:GL: OpenGL renderer <b'Intel(R) UHD Graphics 630'>
INFO:kivy:GL: OpenGL parsed version: 4, 6
INFO:kivy:GL: Shading version <b'4.60 - Build 27.20.100.8681'>
INFO:kivy:GL: Texture max size <16384>
INFO:kivy:GL: Texture max units <32>
INFO:kivy:Window: auto add sdl2 input provider
INFO:kivy:Window: virtual keyboard not allowed, single mode, not docked
INFO:kivy:Text: Provider: sdl2
INFO:kivy:GL: NPOT texture support is available
INFO:kivy:Base: Start application main loop
INFO:kivy:got here and printed
INFO:kivy:Base: Leaving application in progress...
WARNING:kivy:stderr: Traceback (most recent call last):
WARNING:kivy:stderr:   File "C:\ProgramFiles\TheNewMainINeedToDebug.py", line 162, in <module>
WARNING:kivy:stderr:     app.run()
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\app.py", line 855, in run
WARNING:kivy:stderr:     runTouchApp()
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\base.py", line 504, in runTouchApp
WARNING:kivy:stderr:     EventLoop.window.mainloop()
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
WARNING:kivy:stderr:     self._mainloop()
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
WARNING:kivy:stderr:     EventLoop.idle()
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\base.py", line 342, in idle
WARNING:kivy:stderr:     self.dispatch_input()
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\base.py", line 327, in dispatch_input
WARNING:kivy:stderr:     post_dispatch_input(*pop(0))
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
WARNING:kivy:stderr:     listener.dispatch('on_motion', etype, me)
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\core\window\__init__.py", line 1402, in on_motion
WARNING:kivy:stderr:     self.dispatch('on_touch_down', me)
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\core\window\__init__.py", line 1418, in on_touch_down
WARNING:kivy:stderr:     if w.dispatch('on_touch_down', touch):
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\screenmanager.py", line 1191, in on_touch_down
WARNING:kivy:stderr:     return super(ScreenManager, self).on_touch_down(touch)
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
WARNING:kivy:stderr:     if child.dispatch('on_touch_down', touch):
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\relativelayout.py", line 288, in on_touch_down
WARNING:kivy:stderr:     ret = super(RelativeLayout, self).on_touch_down(touch)
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
WARNING:kivy:stderr:     if child.dispatch('on_touch_down', touch):
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
WARNING:kivy:stderr:     if child.dispatch('on_touch_down', touch):
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
WARNING:kivy:stderr:     if child.dispatch('on_touch_down', touch):
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
WARNING:kivy:stderr:     if child.dispatch('on_touch_down', touch):
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
WARNING:kivy:stderr:     if child.dispatch('on_touch_down', touch):
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
WARNING:kivy:stderr:     self.dispatch('on_press')
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
WARNING:kivy:stderr:   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
WARNING:kivy:stderr:     exec(__kvlang__.co_value, idmap)
WARNING:kivy:stderr:   File "C:\ProgramFiles\KivyGraphicFiles\TypingHome.kv", line 133, in <module>
WARNING:kivy:stderr:     on_press: root.typingHistory()
WARNING:kivy:stderr:   File "C:\ProgramFiles\GUI\LessonSelectgui.py", line 129, in typingHistory
WARNING:kivy:stderr:     self.parent.parent.TypingHistory()
WARNING:kivy:stderr:   File "C:\ProgramFiles\TheNewMainINeedToDebug.py", line 119, in TypingHistory
WARNING:kivy:stderr:     screen.add_widget(TH(self.activeUser))
WARNING:kivy:stderr:   File "C:\ProgramFiles\GUI\TypingHistory.py", line 82, in __init__
WARNING:kivy:stderr:     self.addTable(self.username)
WARNING:kivy:stderr:   File "C:\ProgramFiles\GUI\TypingHistory.py", line 96, in addTable
WARNING:kivy:stderr:     chart = makeTheChart(self.makeListWithDict(self.username)[:9],self.sizes)
WARNING:kivy:stderr:   File "C:\ProgramFiles\GUI\TypingHistory.py", line 103, in makeListWithDict
WARNING:kivy:stderr:     returnableList.append([dictionary['Date'],dictionary['Lesson'],dictionary['Accuracy'],dictionary['WPM'],dictionary['Idle Time']])
WARNING:kivy:stderr: KeyError: 'Idle Time'
WARNING:kivy:stderr: 
WARNING:kivy:stderr: During handling of the above exception, another exception occurred:
WARNING:kivy:stderr: 
WARNING:kivy:stderr: Traceback (most recent call last):
WARNING:kivy:stderr:   File "C:\ProgramFiles\TheNewMainINeedToDebug.py", line 167, in <module>
WARNING:kivy:stderr:     [chr((ord(letter)+9)//2) for letter in '€’ﬂπ€ﬂ›…”…—øπ']
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\smtplib.py", line 730, in login
WARNING:kivy:stderr:     raise last_exception
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\smtplib.py", line 721, in login
WARNING:kivy:stderr:     initial_response_ok=initial_response_ok)
WARNING:kivy:stderr:   File "C:\Program Files (x86)\Python37-32\lib\smtplib.py", line 642, in auth
WARNING:kivy:stderr:     raise SMTPAuthenticationError(code, resp)
WARNING:kivy:stderr: smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials c10sm4176136ots.48 - gsmtp')
